version: '2'
services:
  web:
    build: .
    command: java -jar -Ddw.server.connector.type=http 001-sample.jar server etc/settings.yml
    ports:
      - 443:8080
    labels:
      - convox.health.path=/admin/healthcheck
      - convox.port.443.protocol=https
      - convox.idle.timeout=15
    environment:
      - PORT=8090
      - SCHENV=Convox
